<a href="https://colab.research.google.com/github/Abhik4004/StudentAttentionModel/blob/main/StudentAttentionRegressionTree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [100]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [101]:
df = pd.read_csv('/content/sbm_qanda_eye_open.csv')
print(df)

    obs   time   Delta   Theta   Alpha1   Alpha2   Beta1   Beta2   Gamma1  \
0     1    5.0  156140   41240    35282    12125    4320    5737     4207   
1     2    6.0   48248   88005    19094     5156    3278    4399     4165   
2     3    7.0   40773   13156    14656     8733    7761    5393     3824   
3     4    8.0   29813   19983     6887     3369    7360    9863     4976   
4     5    9.0    6062   13764     5874      528    8075    3622     1839   
..  ...    ...     ...     ...      ...      ...     ...     ...      ...   
64   65   69.0  211059  140511     6789    15539   18016   11578     5639   
65   66   70.0  330686   23814     8551     7721    3594    2448     1859   
66   67   71.0   17827    5320     7520    13390   13473    8244     7996   
67   68   72.0  453702   46272    15866     9181    7562   10025     5682   
68   69   72.0   32741   39239     5539     6352   13678    7165     4454   

     Gamma2  Attention  Meditation  Derived   totPwr  class   
0      2115 

**Eye Open**

In [102]:
X = df.iloc[4:,2:10].values.astype(int)
y = df.iloc[4:, -5].values.astype(int)

In [119]:
mean = np.mean(y)
print(mean)

65.87692307692308


In [103]:
X

array([[   6062,   13764,    5874,     528,    8075,    3622,    1839,
           2075],
       [  12045,   18372,    7035,    2070,    9562,    6967,    3615,
            858],
       [   2820,    9829,    2071,    3983,   11066,    7412,    2240,
           2371],
       [  10034,    9581,    3254,    5388,    4343,    5815,    3161,
           4204],
       [  59853,   71842,   14657,    5691,    7875,    5472,    4380,
           3084],
       [ 114154,   31525,   17024,   11094,   20615,    7765,    3144,
           3316],
       [  21254,   23898,   17464,    5992,    6048,    6846,    6659,
           2662],
       [   7392,   12148,     881,    5346,    5759,    5130,    5255,
           1466],
       [   2506,    7869,    4835,    2879,    2796,   16053,    2586,
           1551],
       [  11427,   30104,   19973,    2157,    3569,    4291,    5532,
           1036],
       [   5860,    1981,    4456,    2705,    3617,    5109,    3341,
           1247],
       [   3272,   11

In [104]:
y

array([ 60,  69,  87,  87,  74,  67,  56,  54,  83,  78,  91,  91,  83,
        97,  75,  84,  74,  61,  69,  57,  53,  48,  64,  67,  77,  80,
        66,  53,  37,  43,  34,  34,  37,  30,  48,  60,  78,  93,  88,
        84,  77,  60,  64,  56,  57,  67,  61,  75,  80,  77,  91,  90,
       100, 100, 100, 100,  84,  57,  35,  13,   7,  17,  35,  51,  57])

In [105]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [106]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [107]:
x_train

array([[-5.31559667e-01, -4.73498395e-01,  2.58600806e-01,
         7.24998289e-01,  3.49024423e-01,  7.87599908e-01,
        -3.73242743e-01, -2.53502150e-01],
       [-5.38233201e-01, -6.83970704e-01, -4.63893776e-01,
        -5.51357960e-01, -4.25968949e-01,  3.43006761e-02,
        -9.60546501e-01, -4.84056846e-01],
       [-4.35251331e-01, -2.05361389e-01,  7.23790044e-01,
         3.11254474e-01,  4.32946692e-01,  1.31365847e-01,
         1.66623555e+00, -6.94755157e-01],
       [ 3.43786233e-01,  1.72749867e+00,  5.25267464e-01,
         1.45400272e-01, -2.25025105e-01,  2.72525920e-03,
         9.10246931e-01, -6.91997326e-01],
       [-5.40634068e-01, -5.51924683e-01, -6.34907695e-01,
        -2.98195749e-01, -4.28316955e-01, -5.92863954e-01,
         3.26242632e-01, -5.12738292e-01],
       [ 1.36775237e+00,  1.63056212e-01,  2.46007815e+00,
         1.22605011e+00,  3.73413386e-01, -3.04842691e-01,
         1.61963068e+00,  7.48142175e-01],
       [ 2.23792801e+00,  2.092388

In [113]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 5, random_state = 0)
regressor.fit(x_train, y_train)

RandomForestRegressor(n_estimators=5, random_state=0)

In [114]:
y_pred = regressor.predict(x_test)

In [115]:
print(y_pred)

[73.2 86.6 51.4 91.6 90.4 67.4 73.  57.4 43.8 60.6 86.6 81.4 81.  51.4
 70.  69.2 89. ]


In [116]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

-0.5704702680557181